version: '3'

services:

  app:
    container_name: app
    build:
      dockerfile: './docker-image'
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - MG_SERVICE_ENDPOINT=http://0.0.0.0:8080/v1/
      - MG_DB_CONNECTION_STRING=postgres://postgres:postgres@db:5432/postgres
    networks: 
      - backend
  db:
    container_name: db
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./res/sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./res/sql/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql
    networks: 
      - backend

networks:
    backend:
        driver: "bridge"

